### ISSUE TITLE
misleading error messages handling / Possible CSRF detected

### ISSUE THREAD

**Issue by gcloeval** [FusionAuth/fusionauth-spring-security-example#1]
Hello, thank you very much for this example.
There is I believe an issue with how the error messages are handled - either here in example app or in the OpenIDConnectFilter implementation, here is the summary so it can help someone else.

In [https://github.com/FusionAuth/fusionauth-spring-security/blob/master/src/main/java/io/fusionauth/security/OpenIDConnectFilter.java](url)

if an exception happens: 
```
try {
      accessToken = restTemplate.getAccessToken();
    } catch (final OAuth2Exception e) {
      throw new BadCredentialsException("Could not obtain access token", e);
    }
```
the BadCredentialsException will be thrown but by the time it reaches the example application the details are lost - bc default error handler `https://github.com/spring-projects/spring-security/blob/master/web/src/main/java/org/springframework/security/web/authentication/SimpleUrlAuthenticationFailureHandler.java' SimpleUrlAuthenticationFailureHandler will just forward:

```
public void onAuthenticationFailure(HttpServletRequest request,
			HttpServletResponse response, AuthenticationException exception)
			throws IOException, ServletException {

		if (defaultFailureUrl == null) {
			logger.debug("No failure URL set, sending 401 Unauthorized error");

			response.sendError(HttpStatus.UNAUTHORIZED.value(),
				HttpStatus.UNAUTHORIZED.getReasonPhrase());
		}
...
```

This way NOTHING is logged in the logs or cought - so it makes you believe that something is misconfigured on the fusion auth server and you can go in the wrong direction for a long time...
Finally I figured out if you change how to insantiate actual filter in SecurityConfig:

 ```
@Bean
  public OpenIDConnectFilter myFilter() {
    OpenIDConnectFilter filter = new OpenIDConnectFilter("/login");
    filter.setRestTemplate(restTemplate);
    
    //have to set the error handler here on filter itself, cannot do it below during configuration 
    filter.setAuthenticationFailureHandler(filterErrorHandler);
    
    return filter;
  }
```
where filterErrorHandler is:

```
import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.springframework.security.core.AuthenticationException;
import org.springframework.security.web.authentication.SimpleUrlAuthenticationFailureHandler;
import org.springframework.stereotype.Component;

@Component
public class FilterErrorHandler extends SimpleUrlAuthenticationFailureHandler {

	@Override
	public void onAuthenticationFailure(HttpServletRequest request, HttpServletResponse response,
			AuthenticationException exception) throws IOException, ServletException {

		System.out.println("AUTHENTICATION ERROR TRACE: ");
		exception.printStackTrace();
		super.onAuthenticationFailure(request, response, exception);
	}
}
```
**You can see the actual exception, which in my case is "Caused by: error="invalid_request", error_description="Possible CSRF detected - state parameter was required but no statecould be found:"**

So finally now I am at the actual problem - Possible CSRF detected... Let me know if you have any suggestion about this one?
I have manually confirmed via POSTMAN that the server and configuration works (i.e. post http://localhost:9011/oauth2/authorize.... then manually get the code and post it to http://localhost:9011/oauth2/token - I get the token successfully...

Full exception:

`AUTHENTICATION ERROR TRACE:
```
org.springframework.security.authentication.BadCredentialsException: Could not obtain access token
        at io.fusionauth.security.OpenIDConnectFilter.attemptAuthentication(OpenIDConnectFilter.java:51)
        at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthe
nticationProcessingFilter.java:212)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.oauth2.client.filter.OAuth2ClientContextFilter.doFilter(OAuth2ClientContextFilte
r.java:60)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistence
Filter.java:105)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebA
syncManagerIntegrationFilter.java:56)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
Caused by: error="invalid_request", error_description="Possible CSRF detected - state parameter was required but no stat
e could be found"
        at org.springframework.security.oauth2.client.token.grant.code.AuthorizationCodeAccessTokenProvider.getParameter
sForTokenRequest(AuthorizationCodeAccessTokenProvider.java:255)
        at org.springframework.security.oauth2.client.token.grant.code.AuthorizationCodeAccessTokenProvider.obtainAccess
Token(AuthorizationCodeAccessTokenProvider.java:209)
        at org.springframework.security.oauth2.client.token.AccessTokenProviderChain.obtainNewAccessTokenInternal(Access
TokenProviderChain.java:148)
        at org.springframework.security.oauth2.client.token.AccessTokenProviderChain.obtainAccessToken(AccessTokenProvid
erChain.java:121)
        at org.springframework.security.oauth2.client.OAuth2RestTemplate.acquireAccessToken(OAuth2RestTemplate.java:221)

        at org.springframework.security.oauth2.client.OAuth2RestTemplate.getAccessToken(OAuth2RestTemplate.java:173)
        at io.fusionauth.security.OpenIDConnectFilter.attemptAuthentication(OpenIDConnectFilter.java:47)
        ... 55 more`
```

**Comment by gcloeval** [comment]
Hello - I would like to give you some more information about this based on my investigations. 
I am sure that the issue happens once fusionauth server redirects back to the login after user authenticates. 
I have done the following - instead of sending to fusionauth, I have created a test google OpenID account request. If i use those values and send to googles oath server, this issue does not happen and I  retrieve the user information (if you want to try you can use my test data below its from a test account):
```
fusionAuth.clientId=465878133226-umeoshuobkfu82meieosmmcf7rmf5mr5.apps.googleusercontent.com
fusionAuth.clientSecret=RM-IfsMF9e712w9vHyOOAql9
fusionAuth.accessTokenUri=https://www.googleapis.com/oauth2/v3/token
fusionAuth.logoutUri=http://localhost:9011/oauth2/logout
fusionAuth.userAuthorizationUri=https://accounts.google.com/o/oauth2/auth
fusionAuth.userInfoUri=http://localhost:9011/oauth2/userinfo
fusionAuth.redirectUri=http://localhost:8081/login
```
So all the code is the same, if I now point back to fusionauth server, we get that exception.

Furthermore, I have added some log statements to the spring OAuth2RestTemplate class, specifically in the acquireAccessToken I log out the classId of the oath client context, something like this:

```
protected OAuth2AccessToken acquireAccessToken(OAuth2ClientContext oauth2Context)
			throws UserRedirectRequiredException {
		
		System.out.println("-----modified CUSTOM REST TEMPLATE--, context class =" + oauth2Context.toString());
```

Now in the log files when running successful google scenario, I see that its the same instance (184a4b07 and 184a4b07) of the client context class before and after redirect:
GOOGLE SERVER:
```
-----modified CUSTOM REST TEMPLATE--, context class =org.springframework.security.oauth2.client.DefaultOAuth2ClientConte
xt@184a4b07
-----modified CUSTOM REST TEMPLATE--, context class =org.springframework.security.oauth2.client.DefaultOAuth2ClientConte
xt@184a4b07

```
However, when I run the same scenario with fusionauth, notice that the class is different 55b8faa0 vs 505bf3ec 
```
-----modified CUSTOM REST TEMPLATE--, context class =org.springframework.security.oauth2.client.DefaultOAuth2ClientConte
xt@55b8faa0
------------------INSTANTIATING NEW DefaultOAuth2ClientContext with accessTokenRequest
-----modified CUSTOM REST TEMPLATE--, context class =org.springframework.security.oauth2.client.DefaultOAuth2ClientConte
xt@505bf3ec
```

I dont know much about spring context - is it possible that somehow between the two it is not able to correlate that this should all be part of the same context?
Hope that helps you.
What I dont understand is how can this issue possibly not be happening on your machine? I redid the whole scenario on another laptop and got the same error....

**Comment by tyduptyler13** [comment]
Hi,

We are working to resolve the issue.

We have reproduced the issue and are investigating the two things that have changed since this example was written. The first was an automatic update of the spring dependency via github, and the second was FusionAuth itself. We created some [larger features](https://fusionauth.io/docs/v1/tech/release-notes/#version-1-1-0) that affected OAuth and OpenID workflows.

We will get back to you when we figure out the exact issue.

**Comment by tyduptyler13** [comment]
After lots of digging around and some bug fixing, I found that fusionauth running on localhost is an issue. The reason I didn't see it while I was testing is that I have a local nginx server and some host file changes that allow me to test my instance on its own local domain (instead of localhost). 

To avoid this issue, fusionauth and the example MUST run on different domains or you will have to modify the example to run in a subdirectory. For more info on this checkout the related [issue](https://github.com/spring-projects/spring-security-oauth/issues/322).

I have successfully logged in and registered with my fusionauth instance running on its own domain so I believe this issue is resolved. Let me know if you have any concerns or questions.

**Comment by robotdan** [comment]
The root issue looks to be that both services are using the same session cookie name `JSESSIONID`.  

They collide because they are both on the same host, in this case `localhost`. 

Suggested resolution: 

1. Since the README indicates both services running on `localhost` we could update the `README` to ensure others do not run into this issue.

2. Perhaps a better solution is to update the example to use a different session cookie name so it will be less likely to collide with another service.

For option 2, you could add the following value to the configuration: 

```
server.servlet.session.cookie.name = SPRINGJSESSIONID
```

**Comment by tyduptyler13** [comment]
Confirmed that adding that config allows both services to coexist on the same domain.

**Comment by scopendo** [comment]
I've just come across this same issue following the FusionAuth [blog post](https://fusionauth.io/blog/2018/10/24/easy-integration-of-fusionauth-and-spring).  Probably worth updating the post.
